# -*- coding: utf-8 -*-
"""
fast_cody.apps.convert_to_msh
---------------------------------
Step 2 of the pipeline:

Takes a .glb file generated by Hunyuan, extracts .obj and texture,
then runs fTetWild (or TetWild) to output .msh ready for Fast Cody.
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path
from typing import Optional, Tuple


def find_tetwild() -> Optional[str]:
    """
    Locate fTetWild (FloatTetwild_bin) binary in common paths or $PATH.

    Returns:
        str: Absolute path to fTetWild executable, or None if not found.
    """
    # User's specific fTetWild installation
    user_ftetwild = "/Users/dianne/Desktop/MIT/Graphics_final_project/fTetWild/build/FloatTetwild_bin"
    if os.path.isfile(user_ftetwild) and os.access(user_ftetwild, os.X_OK):
        return os.path.abspath(user_ftetwild)

    # Common installation paths for fTetWild
    common_paths = [
        "~/fTetWild/build/FloatTetwild_bin",
        "~/ftetwild/build/FloatTetwild_bin",
        "~/TetWild/build/FloatTetwild_bin",
        "/usr/local/bin/FloatTetwild_bin",
        "/usr/bin/FloatTetwild_bin",
        "/opt/fTetWild/build/FloatTetwild_bin",
        # Also check for TetWild (fallback)
        "/usr/local/bin/TetWild",
        "/usr/bin/TetWild",
        "~/TetWild/build/TetWild",
    ]

    # Check common paths
    for path in common_paths:
        expanded = os.path.expanduser(path)
        if os.path.isfile(expanded) and os.access(expanded, os.X_OK):
            return os.path.abspath(expanded)

    # Check $PATH for FloatTetwild_bin
    ftetwild = shutil.which("FloatTetwild_bin")
    if ftetwild:
        return ftetwild

    # Check $PATH for fTetWild
    ftetwild_alt = shutil.which("fTetWild")
    if ftetwild_alt:
        return ftetwild_alt

    # Check $PATH for TetWild (fallback)
    tetwild = shutil.which("TetWild")
    if tetwild:
        return tetwild

    return None


def glb_to_obj(glb_path: str, out_dir: Path) -> Tuple[Optional[str], Optional[str]]:
    """
    Convert GLB file to OBJ format and extract texture.

    Args:
        glb_path: Path to input GLB file.
        out_dir: Output directory for OBJ and texture files.

    Returns:
        tuple: (obj_path, texture_path) - both may be None on failure.
    """
    glb_path = Path(glb_path).resolve()
    if not glb_path.exists():
        raise FileNotFoundError(f"GLB file not found: {glb_path}")

    obj_path = out_dir / "model.obj"
    texture_path = out_dir / "texture.png"

    # Try Python libraries first (preferred)
    try:
        import trimesh

        print(f"[CONVERT] Loading GLB with trimesh: {glb_path}")
        scene = trimesh.load(str(glb_path), file_type="glb")

        # Handle both Scene and Mesh objects
        if isinstance(scene, trimesh.Scene):
            # Get the first mesh from the scene
            if len(scene.geometry) == 0:
                raise ValueError("GLB file contains no geometry")
            mesh = list(scene.geometry.values())[0]
        else:
            mesh = scene

        # Export to OBJ
        print(f"[CONVERT] Exporting OBJ to: {obj_path}")
        mesh.export(str(obj_path))

        # Try to extract texture
        if hasattr(mesh.visual, "material"):
            material = mesh.visual.material
            if hasattr(material, "image") and material.image is not None:
                print(f"[CONVERT] Extracting texture to: {texture_path}")
                material.image.save(str(texture_path))
                return str(obj_path), str(texture_path)
            elif hasattr(material, "main_color"):
                # No texture, but we have the OBJ
                print(f"[CONVERT] No texture found in GLB, OBJ exported successfully")
                return str(obj_path), None

        return str(obj_path), None

    except ImportError:
        print("[CONVERT] trimesh not available, trying alternative methods...")
    except Exception as e:
        print(f"[CONVERT] trimesh conversion failed: {e}")
        print("[CONVERT] Falling back to Blender CLI...")

    # Fallback: Try Blender CLI
    blender_path = shutil.which("blender")
    if blender_path:
        try:
            print(f"[CONVERT] Using Blender CLI: {blender_path}")

            # Create a temporary Python script for Blender
            import tempfile

            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".py", delete=False
            ) as script:
                script.write(
                    f"""
import bpy
import os

# Clear default scene
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete()

# Import GLB
bpy.ops.import_scene.gltf(filepath=r'{glb_path}')

# Export OBJ with texture copying
bpy.ops.export_scene.obj(
    filepath=r'{obj_path}',
    path_mode='COPY',
    check_existing=False
)

# Try to extract texture if available
for img in bpy.data.images:
    if img.filepath:
        img_path = bpy.path.abspath(img.filepath)
        if os.path.exists(img_path):
            import shutil
            shutil.copy2(img_path, r'{texture_path}')
            break
"""
                )
                script_path = script.name

            # Run Blender headlessly
            result = subprocess.run(
                [
                    blender_path,
                    "--background",
                    "--python",
                    script_path,
                ],
                capture_output=True,
                text=True,
                check=False,
            )

            # Clean up script
            os.unlink(script_path)

            if result.returncode != 0:
                print(f"[CONVERT] Blender error: {result.stderr}")
                raise RuntimeError("Blender conversion failed")

            if obj_path.exists():
                texture_exists = texture_path.exists()
                print(f"[CONVERT] Blender conversion successful")
                return str(obj_path), str(texture_path) if texture_exists else None
            else:
                raise RuntimeError("Blender did not produce OBJ file")

        except FileNotFoundError:
            print("[CONVERT] Blender not found in PATH")
        except Exception as e:
            print(f"[CONVERT] Blender conversion failed: {e}")

    # If all methods fail
    raise RuntimeError(
        "Failed to convert GLB to OBJ. Install trimesh (pip install trimesh) or Blender."
    )


def convert_to_msh(
    obj_path: str, out_dir: Path, tetwild_path: Optional[str] = None
) -> str:
    """
    Run fTetWild (FloatTetwild_bin) on OBJ file to generate MSH.

    Args:
        obj_path: Path to input OBJ file.
        out_dir: Output directory for MSH file and logs.
        tetwild_path: Optional path to fTetWild executable.

    Returns:
        str: Absolute path to generated MSH file.
    """
    obj_path = Path(obj_path).resolve()
    if not obj_path.exists():
        raise FileNotFoundError(f"OBJ file not found: {obj_path}")

    # Find fTetWild if not provided
    if not tetwild_path:
        tetwild_path = find_tetwild()
        if not tetwild_path:
            raise RuntimeError(
                "fTetWild (FloatTetwild_bin) not found. Please install fTetWild or provide path with --tetwild"
            )

    tetwild_path = Path(tetwild_path).resolve()
    if not tetwild_path.exists():
        raise FileNotFoundError(f"fTetWild executable not found: {tetwild_path}")

    msh_path = out_dir / "model.msh"
    log_dir = out_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "tetwild.log"

    print(f"[CONVERT] Running fTetWild: {tetwild_path}")
    print(f"[CONVERT] Input: {obj_path}")
    print(f"[CONVERT] Output: {msh_path}")

    try:
        # Run fTetWild with the same command format as user's example
        # Format: ./build/FloatTetwild_bin -i input.obj -o output.msh
        with open(log_path, "w") as log_file:
            result = subprocess.run(
                [
                    str(tetwild_path),
                    "-i",
                    str(obj_path),
                    "-o",
                    str(msh_path),
                ],
                capture_output=True,
                text=True,
                check=True,
                cwd=str(tetwild_path.parent.parent) if tetwild_path.name == "FloatTetwild_bin" else None,
            )

            # Write logs
            log_file.write("=== STDOUT ===\n")
            log_file.write(result.stdout)
            log_file.write("\n=== STDERR ===\n")
            log_file.write(result.stderr)

        if not msh_path.exists():
            raise RuntimeError(f"fTetWild did not produce MSH file at {msh_path}")

        print(f"[CONVERT] fTetWild meshing complete → {msh_path}")
        return str(msh_path.resolve())

    except subprocess.CalledProcessError as e:
        error_msg = f"fTetWild failed with return code {e.returncode}\n"
        error_msg += f"STDOUT: {e.stdout}\n"
        error_msg += f"STDERR: {e.stderr}\n"
        error_msg += f"See full log at: {log_path}"

        # Write error to log
        with open(log_path, "w") as log_file:
            log_file.write(error_msg)

        raise RuntimeError(error_msg)


def convert_glb_to_msh(
    glb_path: str, out_dir: str = "outputs/converted", tetwild_path: Optional[str] = None
) -> str:
    """
    Full pipeline: Convert GLB → OBJ(+texture) → MSH.

    Args:
        glb_path: Path to input GLB file.
        out_dir: Base output directory.
        tetwild_path: Optional path to TetWild executable.

    Returns:
        str: Absolute path to generated MSH file.
    """
    # 1. Validate input and create output directory
    glb_path = Path(glb_path).resolve()
    if not glb_path.exists():
        raise FileNotFoundError(f"GLB file not found: {glb_path}")

    # Create output directory based on GLB basename
    glb_stem = glb_path.stem
    out_root = Path(out_dir).resolve()
    job_dir = out_root / glb_stem
    job_dir.mkdir(parents=True, exist_ok=True)

    print(f"[CONVERT] Input GLB: {glb_path}")
    print(f"[CONVERT] Output directory: {job_dir}")

    # 2. Convert GLB to OBJ + texture
    obj_path, texture_path = glb_to_obj(str(glb_path), job_dir)
    print(f"[CONVERT] Extracted OBJ at {obj_path}")
    if texture_path:
        print(f"[CONVERT] Texture at {texture_path}")
    else:
        print("[CONVERT] No texture extracted")

    # 3. Convert OBJ to MSH
    msh_path = convert_to_msh(obj_path, job_dir, tetwild_path)

    print(f"[CONVERT] ✅ Pipeline complete: {msh_path}")
    return msh_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Convert GLB to MSH via OBJ using TetWild"
    )
    parser.add_argument(
        "--glb", required=True, help="Path to input GLB file"
    )
    parser.add_argument(
        "--out",
        default="outputs/converted",
        help="Output directory (default: outputs/converted)",
    )
    parser.add_argument(
        "--tetwild",
        default=None,
        help="Path to fTetWild (FloatTetwild_bin) executable (auto-detected if not provided)",
    )
    args = parser.parse_args()

    try:
        result = convert_glb_to_msh(args.glb, args.out, args.tetwild)
        print(f"✅ Model converted: {result}")
        sys.exit(0)
    except Exception as e:
        print(f"❌ Conversion failed: {e}", file=sys.stderr)
        sys.exit(1)
