import os
import numpy as np
import scipy as sp
import igl
import json
import random
from os.path import basename, splitext


import fast_cd_pyb as fcd
import fast_cody as fc


def load_floor_mesh(floor_path):
    """
    Load and process a floor mesh (OBJ file).
    Returns: (V, F, TC, FTC) or None if failed
    """
    if not os.path.exists(floor_path):
        return None

    try:
        [V_floor, TC_floor, N_floor, F_floor, FTC_floor, FN_floor] = fcd.readOBJ_tex(floor_path)

        # Triangulate quads if needed
        if F_floor.shape[1] == 4:
            num_quads = F_floor.shape[0]
            F_floor_tri = np.zeros((num_quads * 2, 3), dtype=np.int32)
            F_floor_tri[0::2, :] = F_floor[:, [0, 1, 2]]
            F_floor_tri[1::2, :] = F_floor[:, [0, 2, 3]]
            F_floor = F_floor_tri

            if FTC_floor is not None and FTC_floor.shape[1] == 4:
                FTC_tri = np.zeros((num_quads * 2, 3), dtype=np.int32)
                FTC_tri[0::2, :] = FTC_floor[:, [0, 1, 2]]
                FTC_tri[1::2, :] = FTC_floor[:, [0, 2, 3]]
                FTC_floor = FTC_tri

        F_floor = np.ascontiguousarray(F_floor, dtype=np.int32)
        return (V_floor, F_floor, TC_floor, FTC_floor)
    except Exception as e:
        print(f"  Warning: Failed to load {floor_path}: {e}")
        return None


def interactive_cd_affine_handle(msh_file=None, V=None, T=None, Ws=None, l=None, mu=1e4, rho=1e3,
                                 num_modes=16, num_clusters=100,
                                 constraint_enforcement="optimal",
                                 cache_dir=None, results_dir=None, read_cache=False,
                                 texture_png=None, texture_obj=None, enable_caustics=False,
                                 enable_water_surface=False):
    """
    Runs a standard interactive fast CD simulation, where the user can manipulate a single affine
    handle with a Guizmo and observe secondary effects in real-time.

    Parameters
    ----------
    msh_file : str
        path to Tet mesh .msh file (usually generated by TetWild). If None, expects V and T to be provided.
    V : (n, 3) float numpy array
        n x 3 vertex positions. If None, expects msh_file to be provided.
    T : (t, 4) int numpy array.
        t x 4 tet indices. If None, expects msh_file to be provided.
    Ws : (n, m) float numpy array
        n x m skinning weights used for simulation. If None, recomputed on the fly
    l : (t, 1) int numpy array
        T x 1  per-tet cluster indices. if None, recomputed on the fly.
    num_modes : int
        if Ws is None, number of skinning modes to compute
    num_clusters : int
        if l is None, number of skinning clusters to compute.
    constraint_enforcements : str
        {"project", "optimal"}.
        if "optimal", performs the full constrained GEVP described in the paper.
    cache_dir : str
        directory where results are stored and where cache is stored. if None, then
    read_cache : bool
        whether to read skinning modes from cache or not (default=False)
    texture_obj : str
        directory pointing towards a .obj file of the surface mesh
        containing the UV map required for texture mapping. If None and if texture_png is None, then no texturing is applied.
    texture_png : str
        directory pointing towards a .png file of the surface texture.
        if None and if texture_obj is None, then no texturing is applied.
    enable_caustics : bool
        if True, adds animated caustics light patterns on the ocean floor (default=False)
    enable_water_surface : bool
        if True, adds an animated water surface geometry above the scene (default=False)


    Examples
    --------
    >>> import fast_cody as fcd
    >>> fcd.apps.interactive_cd_affine_handle()
    >>> fcd.apps.interactive_cd_affine_handle(enable_caustics=True, enable_water_surface=True)
    """

    if msh_file is not None:
        [V, F, T] = fcd.readMSH(msh_file)
    elif msh_file is None and (V is None and T is None):
        msh_file = fc.get_data("./cd_fish.msh")
        [V, F, T] = fcd.readMSH(msh_file)
    else:
        assert(V is not None and T is not None and "Must provide either msh_file or V and T")

    if texture_png is None or texture_obj is None:
        if msh_file ==  fc.get_data("./cd_fish.msh"):
            texture_png = fc.get_data("./cd_fish_tex.png")
            texture_obj = fc.get_data("./cd_fish_tex.obj")

    if cache_dir is None:
        cache_dir = "./cache/"
    os.makedirs(cache_dir, exist_ok=True)

    [V, so, to] = fcd.scale_and_center_geometry(V, 1, np.array([[0, 0,  0.]])) #center to unit height and about origin

    Wp = np.ones((V.shape[0], 1)) #single handle skinning weight
    J = fc.lbs_jacobian(V, Wp)


    if Ws is None or l is None:
        C = fc.complementary_constraint_matrix(V, T, J, dt=1e-3)
        C2 = fc.lbs_weight_space_constraint(V, C)
        [B, l, Ws] = fc.skinning_subspace(V, T, num_modes, num_clusters, C=C2, read_cache=read_cache,
                                         cache_dir=cache_dir, constraint_enforcement=constraint_enforcement);
    else:
        assert (Ws is not None and l is not None and "Secondary skinning weights and clusters need both be specified")
        num_modes = Ws.shape[1]
        num_clusters = l.max() + 1

    sim = fc.fast_cd_sim(V, T, B, l, J, mu=mu, rho=rho, h=1e-2, cache_dir=cache_dir, read_cache=read_cache)

    # set sim state and initial rig parameters
    z0 = np.zeros((num_modes*12, 1))
    T0 = np.identity(4).astype( dtype=np.float32, order="F");
    p0 = T0[0:3, :].reshape((12, 1))
    st = fc.fast_cd_state(z0, p0)

    step = 0
    floor_ids_ref = [[]]  # List of floor tile IDs
    floor_transforms_ref = [{}]  # Dictionary mapping floor_id -> (p0, z0)
    caustics_data_ref = [{}]  # Dictionary for caustics animation data
    water_surface_id_ref = [None]  # ID for water surface mesh
    camera_mode = ['third_person']  # 'third_person' or 'first_person'
    current_fish_pos = [np.array([0.0, 0.0, 0.0])]  # Store just the fish position (updated each frame)
    control_mode = ['guizmo']  # 'guizmo' or 'keyboard'
    keyboard_velocity = [np.array([0.0, 0.0, 0.0])]  # Current keyboard movement velocity

    # Camera update functions
    def update_third_person_camera():
        """Static third-person camera above the floor"""
        camera_eye = np.array([[0.0, 2.5, 5.0]])  # Above and behind (row vector)
        camera_center = np.array([[0.0, 0.0, 0.0]])  # Look at origin (row vector)

        viewer.viewer.set_camera_eye(camera_eye)
        viewer.viewer.set_camera_center(camera_center)

    def update_first_person_camera():
        """Camera that follows behind the fish using its orientation"""
        # Get the current fish transform from viewer.T0 (the guizmo transform)
        # Extract translation (position)
        fish_pos_current = np.array([viewer.T0[0, 3], viewer.T0[1, 3], viewer.T0[2, 3]])

        # Extract rotation matrix (3x3) from the transform
        R = viewer.T0[0:3, 0:3]

        # The forward direction of the fish is the first column (X-axis in local space)
        # To go behind the fish, we go in the negative forward direction
        forward = R[:, 0]  # Fish's forward direction
        right = R[:, 1]    # Fish's right direction
        up = R[:, 2]       # Fish's up direction

        # Update stored position with smoothing to avoid jerky camera movement
        alpha = 0.15  # Smoothing factor (lower = smoother but more lag)
        current_fish_pos[0] = alpha * fish_pos_current + (1 - alpha) * current_fish_pos[0]
        fish_pos = current_fish_pos[0]

        # Debug: print fish orientation every 60 frames
        if step % 60 == 0:
            print(f"\n=== First-Person Camera (step {step}) ===")
            print(f"Fish position: [{fish_pos[0]:.3f}, {fish_pos[1]:.3f}, {fish_pos[2]:.3f}]")
            print(f"Forward: [{forward[0]:.3f}, {forward[1]:.3f}, {forward[2]:.3f}]")

        # Camera positioned behind and slightly above the fish
        # Using the fish's local coordinate system for proper following
        camera_distance = 2.5    # Distance behind the fish
        camera_height = 0.8      # Height above the fish

        # Position camera behind fish (negative forward direction) and above
        camera_eye = fish_pos - forward * camera_distance + up * camera_height

        # Camera looks at a point slightly ahead of the fish for better view
        look_ahead_distance = 1.0
        camera_center = fish_pos + forward * look_ahead_distance

        # Debug: print camera info
        if step % 60 == 0:
            print(f"Camera eye: [{camera_eye[0]:.3f}, {camera_eye[1]:.3f}, {camera_eye[2]:.3f}]")
            print(f"Camera looking at: [{camera_center[0]:.3f}, {camera_center[1]:.3f}, {camera_center[2]:.3f}]")
            print("="*50)

        # Convert to row vectors (1, 3)
        camera_eye_row = camera_eye.reshape(1, 3)
        camera_center_row = camera_center.reshape(1, 3)

        viewer.viewer.set_camera_eye(camera_eye_row)
        viewer.viewer.set_camera_center(camera_center_row)

    def pre_draw_callback():
         nonlocal J, B, T0, sim, st, step

         # Apply keyboard movement if in keyboard control mode
         if control_mode[0] == 'keyboard':
             # Apply velocity to the fish position
             movement_speed = 0.05  # Units per frame
             velocity = keyboard_velocity[0] * movement_speed

             # Update the transform matrix with new position
             viewer.T0[0, 3] += velocity[0]  # X translation
             viewer.T0[1, 3] += velocity[1]  # Y translation
             viewer.T0[2, 3] += velocity[2]  # Z translation

         # Get the current fish transform from the guizmo/user input or keyboard
         p = viewer.T0[0:3, :].reshape( (12, 1))
         z = sim.step( p, st)
         st.update(z, p)

         # Extract just the translation (last column of the 3x4 transform)
         # p is stored in Fortran order: [R11, R21, R31, R12, R22, R32, R13, R23, R33, tx, ty, tz]
         fish_pos = np.array([p[9, 0], p[10, 0], p[11, 0]])
         current_fish_pos[0] = fish_pos

         # U = np.reshape(J @ p + B @ z, (J.shape[0]//3, 3), order="F") # full positions
         viewer.update_subspace_coefficients(z, p)

         # Update time uniform for caustics animation if enabled
         # Set for ALL meshes (fish + floor) so caustics work on everything
         if enable_caustics and hasattr(viewer.viewer, 'set_uniform'):
             import time as time_module
             if not hasattr(pre_draw_callback, 'start_time'):
                 pre_draw_callback.start_time = time_module.time()
             current_time = time_module.time() - pre_draw_callback.start_time

             # Set time uniform for fish (mesh 0)
             viewer.viewer.set_uniform("u_time", float(current_time), 0)

             # Set time uniform for all floor meshes
             for floor_id in floor_ids_ref[0]:
                 viewer.viewer.set_uniform("u_time", float(current_time), floor_id)

         # Update all floor tiles
         for floor_id in floor_ids_ref[0]:
             if floor_id in floor_transforms_ref[0]:
                 p0_floor, z0_floor = floor_transforms_ref[0][floor_id]

                # Caustics are now handled in the shader as an overlay, no need to swap textures
                # The shader uses u_causticsAtlas uniform which is set up separately

                 viewer.viewer.set_bone_transforms(p0_floor, z0_floor, floor_id)
                 viewer.viewer.updateGL(floor_id)

         # Animate water surface if enabled
         if enable_water_surface and water_surface_id_ref[0] is not None:
             water_id = water_surface_id_ref[0]
             water_info = caustics_data_ref[0].get('water_surface', None)
             if water_info is not None:
                 V_water_base = water_info['V_base']

                 # Create wave animation
                 time = step * 0.05
                 V_water_animated = V_water_base.copy()

                 # Apply sinusoidal waves
                 for i in range(V_water_animated.shape[0]):
                     x, y, z = V_water_animated[i, :]
                     # Multiple wave frequencies for realistic ocean surface
                     wave1 = 0.02 * np.sin(2.0 * x + time * 2.0) * np.cos(2.0 * z + time * 1.5)
                     wave2 = 0.015 * np.sin(3.5 * x - time * 1.5) * np.cos(1.5 * z - time * 2.0)
                     wave3 = 0.01 * np.sin(5.0 * x + 2.0 * z + time * 3.0)
                     V_water_animated[i, 1] += wave1 + wave2 + wave3

                 # Update the water surface mesh
                 V_water_contig = np.ascontiguousarray(V_water_animated, dtype=np.float64)
                 F_water_contig = np.ascontiguousarray(water_info['F'], dtype=np.int32)
                 viewer.viewer.set_mesh(V_water_contig, F_water_contig, water_id)
                 viewer.viewer.updateGL(water_id)

         # Update camera based on current mode
         if camera_mode[0] == 'first_person':
             update_first_person_camera()
         else:
             update_third_person_camera()

         step += 1

    viewer = fc.viewers.interactive_handle_subspace_viewer(V, T, Wp, Ws,  pre_draw_callback,T0=T0,
                                                 texture_png=texture_png, texture_obj=texture_obj,
                                                 t0=to, s0=so, init_guizmo=True)

    # Set background color to #5FBFD2 (ocean blue/cyan)
    background_color = np.array([95, 191, 210]) / 255.0  # Convert hex to RGB (0-1)
    viewer.viewer.set_background_color(background_color)

    # Add custom key callback for camera switching and keyboard control
    original_callback = viewer.callback_key_pressed

    # Track which keys are currently pressed with frame timestamps
    keys_pressed = {}
    key_press_timeout = 3  # Keys expire after 3 frames if not re-pressed

    def update_keyboard_velocity():
        """Update movement velocity based on currently pressed keys"""
        # Remove stale key presses (older than timeout)
        current_frame = step
        expired_keys = [k for k, frame in keys_pressed.items() if current_frame - frame > key_press_timeout]
        for k in expired_keys:
            del keys_pressed[k]

        vel = np.array([0.0, 0.0, 0.0])

        # WASD keys for horizontal movement
        if ord('w') in keys_pressed or ord('W') in keys_pressed:
            vel[2] -= 1.0  # Forward (negative Z)
        if ord('s') in keys_pressed or ord('S') in keys_pressed:
            vel[2] += 1.0  # Backward (positive Z)
        if ord('a') in keys_pressed or ord('A') in keys_pressed:
            vel[0] -= 1.0  # Left (negative X)
        if ord('d') in keys_pressed or ord('D') in keys_pressed:
            vel[0] += 1.0  # Right (positive X)

        # Q/E for vertical movement
        if ord('q') in keys_pressed or ord('Q') in keys_pressed:
            vel[1] -= 1.0  # Down (negative Y)
        if ord('e') in keys_pressed or ord('E') in keys_pressed:
            vel[1] += 1.0  # Up (positive Y)

        # Arrow keys as alternative
        if 265 in keys_pressed:  # Up arrow
            vel[2] -= 1.0  # Forward
        if 264 in keys_pressed:  # Down arrow
            vel[2] += 1.0  # Backward
        if 263 in keys_pressed:  # Left arrow
            vel[0] -= 1.0  # Left
        if 262 in keys_pressed:  # Right arrow
            vel[0] += 1.0  # Right

        # Normalize velocity if moving diagonally
        vel_magnitude = np.linalg.norm(vel)
        if vel_magnitude > 0:
            vel = vel / vel_magnitude

        keyboard_velocity[0] = vel

    def custom_key_callback(key, modifier):
        # Handle 'K' key for control mode switching
        if key == ord('k') or key == ord('K'):
            if control_mode[0] == 'guizmo':
                control_mode[0] = 'keyboard'
                # Hide guizmo
                if hasattr(viewer, 'guizmo') and viewer.guizmo is not None:
                    viewer.guizmo.visible = False
                print("\n=== Keyboard Control Activated ===")
                print("  W/S     Forward/Backward")
                print("  A/D     Left/Right")
                print("  Q/E     Down/Up")
                print("  Arrows  Alternative movement")
                print("  K       Switch back to Guizmo")
                print("="*35)
            else:
                control_mode[0] = 'guizmo'
                # Show guizmo
                if hasattr(viewer, 'guizmo') and viewer.guizmo is not None:
                    viewer.guizmo.visible = True
                keyboard_velocity[0] = np.array([0.0, 0.0, 0.0])  # Stop movement
                keys_pressed.clear()
                print("Switched to Guizmo control")
            return True

        # Handle 'V' key for camera switching
        if key == ord('v') or key == ord('V'):
            if camera_mode[0] == 'third_person':
                camera_mode[0] = 'first_person'
                print("Switched to first-person camera (follows fish)")
            else:
                camera_mode[0] = 'third_person'
                print("Switched to third-person camera (static overview)")
            return False

        # Handle movement keys in keyboard control mode
        if control_mode[0] == 'keyboard':
            # Mark key as pressed
            keys_pressed[key] = True
            update_keyboard_velocity()
            return True

        # Call original callback for other keys (g, c, etc.)
        return original_callback(key, modifier)

    # Also need to handle key release to stop movement
    def custom_key_release_callback(key, modifier):
        if control_mode[0] == 'keyboard' and key in keys_pressed:
            del keys_pressed[key]
            update_keyboard_velocity()
            return True
        return False

    viewer.viewer.set_key_callback(custom_key_callback)
    # Note: key release callback might not be available in all viewer implementations
    # If available, uncomment the following line:
    # viewer.viewer.set_key_release_callback(custom_key_release_callback)

    print("  k        Toggle Control Mode (Guizmo / Keyboard)")
    print("  v        Toggle Camera View (Third-person / First-person)")

    if enable_caustics:
        print("\n  Water Effects:")
        print("  - Animated caustics light patterns on ocean floor")
    if enable_water_surface:
        print("  - Dynamic water surface waves")

    # === ADD OCEAN FLOOR (5x5 GRID) ===
    # Load and add a 3x3 grid of ocean floor tiles as environment objects
    # Try package data first, then fall back to project root data directory
    # Load both sea_floor.obj and sea_floor2.obj for randomization
    try:
        floor_path1 = fc.get_data("sea_floor.obj")
        floor_path2 = fc.get_data("sea_floor2.obj")
        if not os.path.exists(floor_path1) or not os.path.exists(floor_path2):
            raise FileNotFoundError
    except:
        # Fall back to project root data directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
        floor_path1 = os.path.join(project_root, "data", "sea_floor.obj")
        floor_path2 = os.path.join(project_root, "data", "sea_floor2.obj")

    try:
        floor_texture_path = fc.get_data("sandtexture.jpg")
        if not os.path.exists(floor_texture_path):
            raise FileNotFoundError
    except:
        # Fall back to project root data directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
        floor_texture_path = os.path.join(project_root, "data", "sandtexture.jpg")

    # Load caustics frames if caustics enabled
    caustics_frames = []
    if enable_caustics:
        print("\n=== Loading Caustics Frames ===")
        for i in range(1, 17):  # 16 frames
            caustics_frame_path = fc.get_data(f"caustics/caust_{i:03d}.png")
            if os.path.exists(caustics_frame_path):
                caustics_frames.append(caustics_frame_path)
            else:
                print(f"Warning: Caustics frame {i} not found at {caustics_frame_path}")
                enable_caustics = False
                break
        if caustics_frames:
            print(f"Loaded {len(caustics_frames)} caustics frames")
        print("="*50)

    if os.path.exists(floor_path1) or os.path.exists(floor_path2):
        try:
            print(f"\nLoading ocean floor meshes for randomized 5x5 grid...")

            # Load both floor meshes
            floor_mesh1 = load_floor_mesh(floor_path1)
            floor_mesh2 = load_floor_mesh(floor_path2)

            floor_options = []
            if floor_mesh1 is not None:
                V1, F1, TC1, FTC1 = floor_mesh1
                print(f"  Loaded sea_floor.obj: {V1.shape[0]} vertices, {F1.shape[0]} faces")
                floor_options.append((V1, F1, TC1, FTC1, "sea_floor.obj"))
            if floor_mesh2 is not None:
                V2, F2, TC2, FTC2 = floor_mesh2
                print(f"  Loaded sea_floor2.obj: {V2.shape[0]} vertices, {F2.shape[0]} faces")
                floor_options.append((V2, F2, TC2, FTC2, "sea_floor2.obj"))

            if len(floor_options) == 0:
                raise Exception("Failed to load any floor meshes")

            # Floor tile parameters
            tile_scale = 0.05  # Scale to match fish size
            floor_y_offset = -0.5  # Position just below fish

            # Calculate tile size in world space from all loaded meshes (use max for consistent spacing)
            tile_widths = []
            tile_depths = []
            for V_opt, F_opt, TC_opt, FTC_opt, name in floor_options:
                V_scaled = V_opt * tile_scale
                tile_widths.append(V_scaled[:, 0].max() - V_scaled[:, 0].min())
                tile_depths.append(V_scaled[:, 2].max() - V_scaled[:, 2].min())

            tile_width = max(tile_widths)
            tile_depth = max(tile_depths)

            print(f"  Tile dimensions: width={tile_width:.2f}, depth={tile_depth:.2f}")
            print(f"  Creating 5x5 grid (25 tiles) with randomized floor meshes and overlap...")

            # Create 5x5 grid of floor tiles with overlap to hide seams
            num_bones = 16
            num_modes_floor = 16
            floor_tiles = []

            # Overlap factor: 0.9 means 10% overlap (tiles spaced at 90% of their width/depth)
            overlap_factor = 0.9  # Adjust this (0.85-0.95) to control overlap amount
            tile_spacing_x = tile_width * overlap_factor
            tile_spacing_z = tile_depth * overlap_factor

            # Random seed for reproducibility (optional - remove for different patterns each run)
            random.seed(42)

            for i in range(5):  # rows (Z direction) - 5 rows
                for j in range(5):  # columns (X direction) - 5 columns
                    # Randomly select which floor mesh to use for this tile
                    V_floor_base, F_floor, TC_floor, FTC_floor, mesh_name = random.choice(floor_options)

                    # Calculate tile offset (centered around origin)
                    # For 5x5: indices 0-4, center at 2, so offset = (j - 2) and (i - 2)
                    x_offset = (j - 2) * tile_spacing_x  # -2, -1, 0, 1, 2 -> left to right
                    z_offset = (i - 2) * tile_spacing_z  # -2, -1, 0, 1, 2 -> back to front

                    # Scale and translate vertices
                    V_floor_scaled = V_floor_base * tile_scale
                    V_floor_tile = V_floor_scaled.copy()
                    V_floor_tile[:, 0] += x_offset
                    V_floor_tile[:, 1] += floor_y_offset
                    V_floor_tile[:, 2] += z_offset
                    V_floor_tile = np.ascontiguousarray(V_floor_tile, dtype=np.float64)

                    # Add floor mesh
                    floor_id = viewer.viewer.add_mesh()
                    viewer.viewer.set_mesh(V_floor_tile, F_floor, floor_id)

                    # Set texture if available - always use floor texture, caustics overlay in shader
                    use_texture = (os.path.exists(floor_texture_path) and
                                  TC_floor is not None and FTC_floor is not None and
                                  TC_floor.shape[0] > 0 and FTC_floor.shape[0] > 0)
                    if use_texture:
                        try:
                            TC_contig = np.ascontiguousarray(TC_floor, dtype=np.float64)
                            FTC_contig = np.ascontiguousarray(FTC_floor, dtype=np.int32)
                            # Always use floor texture - caustics will be overlaid in shader
                            viewer.viewer.set_texture(floor_texture_path, TC_contig, FTC_contig, floor_id)
                        except Exception as e:
                            print(f"  Warning: Could not apply texture to tile ({i},{j}): {e}")

                    # Set weights - bind all vertices to bone 0 with weight 1.0
                    num_verts = V_floor_tile.shape[0]
                    Wp_floor = np.zeros((num_verts, num_bones), dtype=np.float64)
                    Wp_floor[:, 0] = 1.0  # All vertices fully bound to bone 0 (identity)
                    Ws_floor = np.zeros((num_verts, num_modes_floor), dtype=np.float64)
                    viewer.viewer.set_weights(Wp_floor, Ws_floor, floor_id)

                    # Set rendering options AFTER weights
                    if use_texture:
                        viewer.viewer.set_show_lines(False, floor_id)
                        viewer.viewer.set_face_based(False, floor_id)
                    else:
                        floor_color = np.array([200, 180, 150]) / 255.0
                        viewer.viewer.set_color(floor_color, floor_id)
                        viewer.viewer.set_face_based(True, floor_id)
                        viewer.viewer.invert_normals(True, floor_id)
                        viewer.viewer.set_show_lines(False, floor_id)

                    # Initialize static identity bone transforms
                    p0_floor = np.zeros((num_bones * 12, 1), dtype=np.float64)
                    for bone_idx in range(num_bones):
                        base_idx = bone_idx * 12
                        p0_floor[base_idx + 0] = 1.0   # Identity matrix diagonal
                        p0_floor[base_idx + 5] = 1.0
                        p0_floor[base_idx + 10] = 1.0
                    z0_floor = np.zeros((num_modes_floor * 12, 1), dtype=np.float64)

                    viewer.viewer.set_bone_transforms(p0_floor, z0_floor, floor_id)

                    # Store floor ID and transforms
                    floor_ids_ref[0].append(floor_id)
                    floor_transforms_ref[0][floor_id] = (p0_floor, z0_floor)
                    floor_tiles.append((floor_id, i, j, x_offset, z_offset, mesh_name))

                    print(f"  Tile ({i},{j}): mesh ID {floor_id}, offset=({x_offset:.2f}, {z_offset:.2f}), mesh={mesh_name}")

            print(f"\n  Floor grid loaded successfully: {len(floor_tiles)} tiles")
            if enable_caustics and caustics_frames:
                print(f"  Animated caustics enabled ({len(caustics_frames)} frames)")
            print(f"  Floor tiles are static environment objects (not controlled by affine handle)")

        except Exception as e:
            print(f"ERROR: Failed to load ocean floor: {e}")
            import traceback
            traceback.print_exc()
            print("  Continuing without floor...")
    else:
        print(f"Floor files not found: {floor_path1} or {floor_path2}")
        print("Continuing without floor...")
    # =======================

    # === ADD DYNAMIC WATER SURFACE ===
    if enable_water_surface:
        try:
            print("\n=== Adding Dynamic Water Surface ===")

            # Create a grid mesh for the water surface
            grid_size = 50  # Number of vertices per side
            water_extent = 5.0  # Size in world units
            water_y = 1.0  # Height above origin

            # Generate grid vertices
            x_vals = np.linspace(-water_extent, water_extent, grid_size)
            z_vals = np.linspace(-water_extent, water_extent, grid_size)
            xx, zz = np.meshgrid(x_vals, z_vals)

            V_water = np.zeros((grid_size * grid_size, 3), dtype=np.float64)
            V_water[:, 0] = xx.flatten()
            V_water[:, 1] = water_y
            V_water[:, 2] = zz.flatten()

            # Generate grid faces (triangles)
            F_water = []
            for i in range(grid_size - 1):
                for j in range(grid_size - 1):
                    idx = i * grid_size + j
                    # Two triangles per quad
                    F_water.append([idx, idx + 1, idx + grid_size])
                    F_water.append([idx + 1, idx + grid_size + 1, idx + grid_size])
            F_water = np.array(F_water, dtype=np.int32)

            # Add water surface mesh
            water_id = viewer.viewer.add_mesh()
            V_water_contig = np.ascontiguousarray(V_water, dtype=np.float64)
            F_water_contig = np.ascontiguousarray(F_water, dtype=np.int32)
            viewer.viewer.set_mesh(V_water_contig, F_water_contig, water_id)

            # Set water appearance (semi-transparent blue)
            water_color = np.array([0.1, 0.4, 0.7])  # Blue-ish color
            viewer.viewer.set_color(water_color, water_id)
            viewer.viewer.set_face_based(False, water_id)
            viewer.viewer.set_show_lines(True, water_id)  # Show grid lines for water

            # Set weights for water surface
            num_verts_water = V_water.shape[0]
            num_bones = 16
            num_modes_water = 16
            Wp_water = np.zeros((num_verts_water, num_bones), dtype=np.float64)
            Wp_water[:, 0] = 1.0
            Ws_water = np.zeros((num_verts_water, num_modes_water), dtype=np.float64)
            viewer.viewer.set_weights(Wp_water, Ws_water, water_id)

            # Initialize bone transforms
            p0_water = np.zeros((num_bones * 12, 1), dtype=np.float64)
            for bone_idx in range(num_bones):
                base_idx = bone_idx * 12
                p0_water[base_idx + 0] = 1.0
                p0_water[base_idx + 5] = 1.0
                p0_water[base_idx + 10] = 1.0
            z0_water = np.zeros((num_modes_water * 12, 1), dtype=np.float64)
            viewer.viewer.set_bone_transforms(p0_water, z0_water, water_id)

            # Store water surface data
            water_surface_id_ref[0] = water_id
            caustics_data_ref[0]['water_surface'] = {
                'V_base': V_water.copy(),
                'F': F_water.copy()
            }

            print(f"  Water surface mesh created: {V_water.shape[0]} vertices, {F_water.shape[0]} faces")
            print(f"  Grid size: {grid_size}x{grid_size}, extent: {water_extent*2:.1f} units")
            print("="*50)

        except Exception as e:
            print(f"ERROR: Failed to create water surface: {e}")
            import traceback
            traceback.print_exc()
            enable_water_surface = False
    # =======================

    viewer.launch()


def interactive_cd_affine_handle_with_caustics(msh_file=None, V=None, T=None, Ws=None, l=None, mu=1e4, rho=1e3,
                                 num_modes=16, num_clusters=100,
                                 constraint_enforcement="optimal",
                                 cache_dir=None, results_dir=None, read_cache=False,
                                 texture_png=None, texture_obj=None):
    """
    Runs an interactive fast CD simulation with animated water caustics effect on the floor.

    This version adds dynamic caustics lighting that simulates light refracting through
    a water surface, creating the illusion of swimming underwater without full water simulation.

    Parameters are identical to interactive_cd_affine_handle().
    """

    if msh_file is not None:
        [V, F, T] = fcd.readMSH(msh_file)
    elif msh_file is None and (V is None and T is None):
        msh_file = fc.get_data("./cd_fish.msh")
        [V, F, T] = fcd.readMSH(msh_file)
    else:
        assert(V is not None and T is not None and "Must provide either msh_file or V and T")

    if texture_png is None or texture_obj is None:
        if msh_file ==  fc.get_data("./cd_fish.msh"):
            texture_png = fc.get_data("./cd_fish_tex.png")
            texture_obj = fc.get_data("./cd_fish_tex.obj")

    if cache_dir is None:
        cache_dir = "./cache/"
    os.makedirs(cache_dir, exist_ok=True)

    [V, so, to] = fcd.scale_and_center_geometry(V, 1, np.array([[0, 0,  0.]])) #center to unit height and about origin

    Wp = np.ones((V.shape[0], 1)) #single handle skinning weight
    J = fc.lbs_jacobian(V, Wp)


    if Ws is None or l is None:
        C = fc.complementary_constraint_matrix(V, T, J, dt=1e-3)
        C2 = fc.lbs_weight_space_constraint(V, C)
        [B, l, Ws] = fc.skinning_subspace(V, T, num_modes, num_clusters, C=C2, read_cache=read_cache,
                                         cache_dir=cache_dir, constraint_enforcement=constraint_enforcement);
    else:
        assert (Ws is not None and l is not None and "Secondary skinning weights and clusters need both be specified")
        num_modes = Ws.shape[1]
        num_clusters = l.max() + 1

    sim = fc.fast_cd_sim(V, T, B, l, J, mu=mu, rho=rho, h=1e-2, cache_dir=cache_dir, read_cache=read_cache)

    # set sim state and initial rig parameters
    z0 = np.zeros((num_modes*12, 1))
    T0 = np.identity(4).astype( dtype=np.float32, order="F");
    p0 = T0[0:3, :].reshape((12, 1))
    st = fc.fast_cd_state(z0, p0)

    step = 0
    floor_ids_ref = [[]]  # List of floor tile IDs
    floor_transforms_ref = [{}]  # Dictionary mapping floor_id -> (p0, z0)
    caustics_data_ref = [{}]  # Dictionary mapping floor_id -> caustics animation data
    camera_mode = ['third_person']  # 'third_person' or 'first_person'
    current_fish_pos = [np.array([0.0, 0.0, 0.0])]  # Store just the fish position (updated each frame)
    control_mode = ['guizmo']  # 'guizmo' or 'keyboard'
    keyboard_velocity = [np.array([0.0, 0.0, 0.0])]  # Current keyboard movement velocity

    # Camera update functions
    def update_third_person_camera():
        """Static third-person camera above the floor"""
        camera_eye = np.array([[0.0, 2.5, 5.0]])  # Above and behind (row vector)
        camera_center = np.array([[0.0, 0.0, 0.0]])  # Look at origin (row vector)

        viewer.viewer.set_camera_eye(camera_eye)
        viewer.viewer.set_camera_center(camera_center)

    def update_first_person_camera():
        """Camera that follows behind the fish using its orientation"""
        # Get the current fish transform from viewer.T0 (the guizmo transform)
        # Extract translation (position)
        fish_pos_current = np.array([viewer.T0[0, 3], viewer.T0[1, 3], viewer.T0[2, 3]])

        # Extract rotation matrix (3x3) from the transform
        R = viewer.T0[0:3, 0:3]

        # The forward direction of the fish is the first column (X-axis in local space)
        # To go behind the fish, we go in the negative forward direction
        forward = R[:, 0]  # Fish's forward direction
        right = R[:, 1]    # Fish's right direction
        up = R[:, 2]       # Fish's up direction

        # Update stored position with smoothing to avoid jerky camera movement
        alpha = 0.15  # Smoothing factor (lower = smoother but more lag)
        current_fish_pos[0] = alpha * fish_pos_current + (1 - alpha) * current_fish_pos[0]
        fish_pos = current_fish_pos[0]

        # Debug: print fish orientation every 60 frames
        if step % 60 == 0:
            print(f"\n=== First-Person Camera (step {step}) ===")
            print(f"Fish position: [{fish_pos[0]:.3f}, {fish_pos[1]:.3f}, {fish_pos[2]:.3f}]")
            print(f"Forward: [{forward[0]:.3f}, {forward[1]:.3f}, {forward[2]:.3f}]")

        # Camera positioned behind and slightly above the fish
        # Using the fish's local coordinate system for proper following
        camera_distance = 2.5    # Distance behind the fish
        camera_height = 0.8      # Height above the fish

        # Position camera behind fish (negative forward direction) and above
        camera_eye = fish_pos - forward * camera_distance + up * camera_height

        # Camera looks at a point slightly ahead of the fish for better view
        look_ahead_distance = 1.0
        camera_center = fish_pos + forward * look_ahead_distance

        # Debug: print camera info
        if step % 60 == 0:
            print(f"Camera eye: [{camera_eye[0]:.3f}, {camera_eye[1]:.3f}, {camera_eye[2]:.3f}]")
            print(f"Camera looking at: [{camera_center[0]:.3f}, {camera_center[1]:.3f}, {camera_center[2]:.3f}]")
            print("="*50)

        # Convert to row vectors (1, 3)
        camera_eye_row = camera_eye.reshape(1, 3)
        camera_center_row = camera_center.reshape(1, 3)

        viewer.viewer.set_camera_eye(camera_eye_row)
        viewer.viewer.set_camera_center(camera_center_row)

    def pre_draw_callback():
         nonlocal J, B, T0, sim, st, step

         # Apply keyboard movement if in keyboard control mode
         if control_mode[0] == 'keyboard':
             # Apply velocity to the fish position
             movement_speed = 0.05  # Units per frame
             velocity = keyboard_velocity[0] * movement_speed

             # Update the transform matrix with new position
             viewer.T0[0, 3] += velocity[0]  # X translation
             viewer.T0[1, 3] += velocity[1]  # Y translation
             viewer.T0[2, 3] += velocity[2]  # Z translation

         # Get the current fish transform from the guizmo/user input or keyboard
         p = viewer.T0[0:3, :].reshape( (12, 1))
         z = sim.step( p, st)
         st.update(z, p)

         # Extract just the translation (last column of the 3x4 transform)
         # p is stored in Fortran order: [R11, R21, R31, R12, R22, R32, R13, R23, R33, tx, ty, tz]
         fish_pos = np.array([p[9, 0], p[10, 0], p[11, 0]])
         current_fish_pos[0] = fish_pos

         # U = np.reshape(J @ p + B @ z, (J.shape[0]//3, 3), order="F") # full positions
         viewer.update_subspace_coefficients(z, p)

         # Update all floor tiles with animated caustics
         for floor_id in floor_ids_ref[0]:
             if floor_id in floor_transforms_ref[0]:
                 p0_floor, z0_floor = floor_transforms_ref[0][floor_id]

                 # Animate caustics by cycling through atlas frames
                 if floor_id in caustics_data_ref[0]:
                     caustics_info = caustics_data_ref[0][floor_id]
                     num_frames = caustics_info['num_frames']
                     frame_rate = caustics_info['frame_rate']
                     TC_base = caustics_info['TC_base']
                     FTC = caustics_info['FTC']

                     # Calculate current frame (cycle through frames)
                     current_frame = int((step / frame_rate) % num_frames)

                     # Shift UV coordinates to current frame in atlas
                     # Atlas has frames laid out horizontally, so we shift U coordinate
                     frame_offset = current_frame / num_frames
                     TC_animated = TC_base.copy()
                     TC_animated[:, 0] = (TC_base[:, 0] / num_frames) + frame_offset

                     # Update texture coordinates (this requires the viewer to support dynamic UV updates)
                     # Note: If viewer doesn't support this, we'd need to modify the C++ binding
                     try:
                         # Attempt to update texture coordinates dynamically
                         TC_contig = np.ascontiguousarray(TC_animated, dtype=np.float64)
                         FTC_contig = np.ascontiguousarray(FTC, dtype=np.int32)
                         # This assumes the viewer has the texture already loaded, just updating UVs
                         viewer.viewer.set_texture_coords(TC_contig, FTC_contig, floor_id)
                     except AttributeError:
                         # If set_texture_coords doesn't exist, we can't animate dynamically
                         # In this case, caustics will be static (first frame)
                         pass

                 viewer.viewer.set_bone_transforms(p0_floor, z0_floor, floor_id)
                 viewer.viewer.updateGL(floor_id)

         # Update camera based on current mode
         if camera_mode[0] == 'first_person':
             update_first_person_camera()
         else:
             update_third_person_camera()

         step += 1

    viewer = fc.viewers.interactive_handle_subspace_viewer(V, T, Wp, Ws,  pre_draw_callback,T0=T0,
                                                 texture_png=texture_png, texture_obj=texture_obj,
                                                 t0=to, s0=so, init_guizmo=True)

    # Set background color to #5FBFD2 (ocean blue/cyan)
    background_color = np.array([95, 191, 210]) / 255.0  # Convert hex to RGB (0-1)
    viewer.viewer.set_background_color(background_color)

    # Add custom key callback for camera switching and keyboard control
    original_callback = viewer.callback_key_pressed

    # Track which keys are currently pressed with frame timestamps
    keys_pressed = {}
    key_press_timeout = 3  # Keys expire after 3 frames if not re-pressed

    def update_keyboard_velocity():
        """Update movement velocity based on currently pressed keys"""
        # Remove stale key presses (older than timeout)
        current_frame = step
        expired_keys = [k for k, frame in keys_pressed.items() if current_frame - frame > key_press_timeout]
        for k in expired_keys:
            del keys_pressed[k]

        vel = np.array([0.0, 0.0, 0.0])

        # WASD keys for horizontal movement
        if ord('w') in keys_pressed or ord('W') in keys_pressed:
            vel[2] -= 1.0  # Forward (negative Z)
        if ord('s') in keys_pressed or ord('S') in keys_pressed:
            vel[2] += 1.0  # Backward (positive Z)
        if ord('a') in keys_pressed or ord('A') in keys_pressed:
            vel[0] -= 1.0  # Left (negative X)
        if ord('d') in keys_pressed or ord('D') in keys_pressed:
            vel[0] += 1.0  # Right (positive X)

        # Q/E for vertical movement
        if ord('q') in keys_pressed or ord('Q') in keys_pressed:
            vel[1] -= 1.0  # Down (negative Y)
        if ord('e') in keys_pressed or ord('E') in keys_pressed:
            vel[1] += 1.0  # Up (positive Y)

        # Arrow keys as alternative
        if 265 in keys_pressed:  # Up arrow
            vel[2] -= 1.0  # Forward
        if 264 in keys_pressed:  # Down arrow
            vel[2] += 1.0  # Backward
        if 263 in keys_pressed:  # Left arrow
            vel[0] -= 1.0  # Left
        if 262 in keys_pressed:  # Right arrow
            vel[0] += 1.0  # Right

        # Normalize velocity if moving diagonally
        vel_magnitude = np.linalg.norm(vel)
        if vel_magnitude > 0:
            vel = vel / vel_magnitude

        keyboard_velocity[0] = vel

    def custom_key_callback(key, modifier):
        # Handle 'K' key for control mode switching
        if key == ord('k') or key == ord('K'):
            if control_mode[0] == 'guizmo':
                control_mode[0] = 'keyboard'
                # Hide guizmo
                if hasattr(viewer, 'guizmo') and viewer.guizmo is not None:
                    viewer.guizmo.visible = False
                print("\n=== Keyboard Control Activated ===")
                print("  W/S     Forward/Backward")
                print("  A/D     Left/Right")
                print("  Q/E     Down/Up")
                print("  Arrows  Alternative movement")
                print("  K       Switch back to Guizmo")
                print("="*35)
            else:
                control_mode[0] = 'guizmo'
                # Show guizmo
                if hasattr(viewer, 'guizmo') and viewer.guizmo is not None:
                    viewer.guizmo.visible = True
                keyboard_velocity[0] = np.array([0.0, 0.0, 0.0])  # Stop movement
                keys_pressed.clear()
                print("Switched to Guizmo control")
            return True

        # Handle 'V' key for camera switching
        if key == ord('v') or key == ord('V'):
            if camera_mode[0] == 'third_person':
                camera_mode[0] = 'first_person'
                print("Switched to first-person camera (follows fish)")
            else:
                camera_mode[0] = 'third_person'
                print("Switched to third-person camera (static overview)")
            return False

        # Handle movement keys in keyboard control mode
        if control_mode[0] == 'keyboard':
            # Mark key as pressed
            keys_pressed[key] = True
            update_keyboard_velocity()
            return True

        # Call original callback for other keys (g, c, etc.)
        return original_callback(key, modifier)

    # Also need to handle key release to stop movement
    def custom_key_release_callback(key, modifier):
        if control_mode[0] == 'keyboard' and key in keys_pressed:
            del keys_pressed[key]
            update_keyboard_velocity()
            return True
        return False

    viewer.viewer.set_key_callback(custom_key_callback)
    # Note: key release callback might not be available in all viewer implementations
    # If available, uncomment the following line:
    # viewer.viewer.set_key_release_callback(custom_key_release_callback)

    print("  k        Toggle Control Mode (Guizmo / Keyboard)")
    print("  v        Toggle Camera View (Third-person / First-person)")

    # === ADD OCEAN FLOOR WITH CAUSTICS (5x5 GRID) ===
    # Load caustics atlas using fc.get_data() for proper path resolution
    try:
        floor_path1 = fc.get_data("sea_floor.obj")
        floor_path2 = fc.get_data("sea_floor2.obj")
        if not os.path.exists(floor_path1) or not os.path.exists(floor_path2):
            raise FileNotFoundError
    except:
        # Fall back to project root data directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(os.path.dirname(os.path.dirname(script_dir)))
        floor_path1 = os.path.join(project_root, "data", "sea_floor.obj")
        floor_path2 = os.path.join(project_root, "data", "sea_floor2.obj")

    floor_texture_path = fc.get_data("sandtexture.jpg")
    caustics_atlas_path = fc.get_data("caustics/caustics_atlas.png")

    if os.path.exists(floor_path1) or os.path.exists(floor_path2):
        try:
            print(f"\nLoading ocean floor meshes for randomized 5x5 grid with animated caustics...")

            # Load both floor meshes
            floor_mesh1 = load_floor_mesh(floor_path1)
            floor_mesh2 = load_floor_mesh(floor_path2)

            floor_options = []
            if floor_mesh1 is not None:
                V1, F1, TC1, FTC1 = floor_mesh1
                print(f"  Loaded sea_floor.obj: {V1.shape[0]} vertices, {F1.shape[0]} faces")
                floor_options.append((V1, F1, TC1, FTC1, "sea_floor.obj"))
            if floor_mesh2 is not None:
                V2, F2, TC2, FTC2 = floor_mesh2
                print(f"  Loaded sea_floor2.obj: {V2.shape[0]} vertices, {F2.shape[0]} faces")
                floor_options.append((V2, F2, TC2, FTC2, "sea_floor2.obj"))

            if len(floor_options) == 0:
                raise Exception("Failed to load any floor meshes")

            # Floor tile parameters
            tile_scale = 0.05  # Scale to match fish size
            floor_y_offset = -0.5  # Position just below fish

            # Calculate tile size in world space from all loaded meshes (use max for consistent spacing)
            tile_widths = []
            tile_depths = []
            for V_opt, F_opt, TC_opt, FTC_opt, name in floor_options:
                V_scaled = V_opt * tile_scale
                tile_widths.append(V_scaled[:, 0].max() - V_scaled[:, 0].min())
                tile_depths.append(V_scaled[:, 2].max() - V_scaled[:, 2].min())

            tile_width = max(tile_widths)
            tile_depth = max(tile_depths)

            print(f"  Tile dimensions: width={tile_width:.2f}, depth={tile_depth:.2f}")
            print(f"  Creating 5x5 grid (25 tiles) with randomized floor meshes, animated caustics and overlap...")

            # Check if caustics atlas exists
            use_caustics = os.path.exists(caustics_atlas_path)
            if use_caustics:
                print(f"  Loading caustics atlas: {caustics_atlas_path}")
                caustics_num_frames = 16  # Number of frames in the atlas
                caustics_frame_rate = 2.0  # Change frame every N simulation steps (slower = more realistic)
            else:
                print(f"  Warning: Caustics atlas not found at {caustics_atlas_path}")
                print(f"  Falling back to static floor texture")

            # Create 5x5 grid of floor tiles with overlap to hide seams
            num_bones = 16
            num_modes_floor = 16
            floor_tiles = []

            # Overlap factor: 0.9 means 10% overlap (tiles spaced at 90% of their width/depth)
            overlap_factor = 0.9  # Adjust this (0.85-0.95) to control overlap amount
            tile_spacing_x = tile_width * overlap_factor
            tile_spacing_z = tile_depth * overlap_factor

            # Random seed for reproducibility (optional - remove for different patterns each run)
            random.seed(42)

            for i in range(5):  # rows (Z direction) - 5 rows
                for j in range(5):  # columns (X direction) - 5 columns
                    # Randomly select which floor mesh to use for this tile
                    V_floor_base, F_floor, TC_floor, FTC_floor, mesh_name = random.choice(floor_options)

                    # Calculate tile offset (centered around origin)
                    # For 5x5: indices 0-4, center at 2, so offset = (j - 2) and (i - 2)
                    x_offset = (j - 2) * tile_spacing_x  # -2, -1, 0, 1, 2 -> left to right
                    z_offset = (i - 2) * tile_spacing_z  # -2, -1, 0, 1, 2 -> back to front

                    # Scale and translate vertices
                    V_floor_scaled = V_floor_base * tile_scale
                    V_floor_tile = V_floor_scaled.copy()
                    V_floor_tile[:, 0] += x_offset
                    V_floor_tile[:, 1] += floor_y_offset
                    V_floor_tile[:, 2] += z_offset
                    V_floor_tile = np.ascontiguousarray(V_floor_tile, dtype=np.float64)

                    # Add floor mesh
                    floor_id = viewer.viewer.add_mesh()
                    viewer.viewer.set_mesh(V_floor_tile, F_floor, floor_id)

                    # Always use floor texture - caustics will be overlaid in shader
                    use_texture = (os.path.exists(floor_texture_path) and
                                  TC_floor is not None and FTC_floor is not None and
                                  TC_floor.shape[0] > 0 and FTC_floor.shape[0] > 0)
                    if use_texture:
                        try:
                            TC_contig = np.ascontiguousarray(TC_floor, dtype=np.float64)
                            FTC_contig = np.ascontiguousarray(FTC_floor, dtype=np.int32)
                            # Always use floor texture, caustics overlay handled in shader
                            if os.path.exists(floor_texture_path):
                                viewer.viewer.set_texture(floor_texture_path, TC_contig, FTC_contig, floor_id)
                            else:
                                print(f"  Warning: Floor texture not found at {floor_texture_path}")
                        except Exception as e:
                            print(f"  Warning: Could not apply texture to tile ({i},{j}): {e}")

                    # Set weights - bind all vertices to bone 0 with weight 1.0
                    num_verts = V_floor_tile.shape[0]
                    Wp_floor = np.zeros((num_verts, num_bones), dtype=np.float64)
                    Wp_floor[:, 0] = 1.0  # All vertices fully bound to bone 0 (identity)
                    Ws_floor = np.zeros((num_verts, num_modes_floor), dtype=np.float64)
                    viewer.viewer.set_weights(Wp_floor, Ws_floor, floor_id)

                    # Set rendering options AFTER weights
                    if use_texture:
                        viewer.viewer.set_show_lines(False, floor_id)
                        viewer.viewer.set_face_based(False, floor_id)
                    else:
                        floor_color = np.array([200, 180, 150]) / 255.0
                        viewer.viewer.set_color(floor_color, floor_id)
                        viewer.viewer.set_face_based(True, floor_id)
                        viewer.viewer.invert_normals(True, floor_id)
                        viewer.viewer.set_show_lines(False, floor_id)

                    # Initialize static identity bone transforms
                    p0_floor = np.zeros((num_bones * 12, 1), dtype=np.float64)
                    for bone_idx in range(num_bones):
                        base_idx = bone_idx * 12
                        p0_floor[base_idx + 0] = 1.0   # Identity matrix diagonal
                        p0_floor[base_idx + 5] = 1.0
                        p0_floor[base_idx + 10] = 1.0
                    z0_floor = np.zeros((num_modes_floor * 12, 1), dtype=np.float64)

                    viewer.viewer.set_bone_transforms(p0_floor, z0_floor, floor_id)

                    # Store floor ID and transforms
                    floor_ids_ref[0].append(floor_id)
                    floor_transforms_ref[0][floor_id] = (p0_floor, z0_floor)
                    floor_tiles.append((floor_id, i, j, x_offset, z_offset, mesh_name))

                    print(f"  Tile ({i},{j}): mesh ID {floor_id}, offset=({x_offset:.2f}, {z_offset:.2f}), mesh={mesh_name}")

            print(f"\n  Floor grid loaded successfully: {len(floor_tiles)} tiles")
            # Check if caustics atlas exists
            use_caustics = os.path.exists(caustics_atlas_path)
            if use_caustics:
                print(f"  Animated caustics enabled (16 frames)")
            print(f"  Floor tiles are static environment objects (not controlled by affine handle)")

        except Exception as e:
            print(f"ERROR: Failed to load ocean floor: {e}")
            import traceback
            traceback.print_exc()
            print("  Continuing without floor...")
    else:
        print(f"Floor files not found: {floor_path1} or {floor_path2}")
        print("Continuing without floor...")
    # =======================

    # Set up caustics atlas as overlay texture if enabled
    if enable_caustics:
        caustics_atlas_path = fc.get_data("caustics/caustics_atlas.png")
        if os.path.exists(caustics_atlas_path):
            try:
                # Set up caustics atlas as separate texture overlay
                if hasattr(viewer.viewer, 'set_caustics_atlas'):
                    viewer.viewer.set_caustics_atlas(caustics_atlas_path)
                    print(f"  Caustics atlas loaded: {caustics_atlas_path}")

                    # Set shader uniforms for caustics animation
                    # Set for ALL meshes (fish + floor) so caustics work on everything
                    if hasattr(viewer.viewer, 'set_uniform'):
                        # Get all mesh IDs (fish is 0, plus all floor meshes)
                        all_mesh_ids = [0]  # Fish mesh (always ID 0)
                        # Add all floor mesh IDs
                        all_mesh_ids.extend(floor_ids_ref[0])

                        # Set caustics uniforms for all meshes
                        for mesh_id in all_mesh_ids:
                            viewer.viewer.set_uniform("u_numFrames", 16, mesh_id)  # Number of frames in atlas
                            viewer.viewer.set_uniform("u_frameRate", 12.0, mesh_id)  # Animation frame rate
                        print(f"  Caustics shader uniforms configured for {len(all_mesh_ids)} meshes (fish + floor)")
                else:
                    print("  Warning: set_caustics_atlas method not available")
            except Exception as e:
                print(f"  Warning: Failed to set up caustics atlas: {e}")
        else:
            print(f"  Warning: Caustics atlas not found at {caustics_atlas_path}")

    viewer.launch()
